apiVersion: v1
kind: Service
metadata:
  name: devops-portfolio-app
  namespace: devops-portfolio
spec:
  selector:
    app: devops-portfolio-app
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: LoadBalancer
